version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - chmod +x node_modules/.bin/*
      - npm cache clean --force
      - npm install
      - echo "Dependencies installed successfully"
  build:
    commands:
      - echo "Starting build phase..."
      - npm run build
      
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
  base-directory: 'build'

cache:
  paths:
    - 'node_modules/**/*'